name: Test, Build, and Deploy

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  # Job 1: Test and Build
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate PHP Syntax
      run: find . -name "*.php" -exec php -l {} \;

    - name: Run WordPress Coding Standards
      uses: docker://ghcr.io/squizlabs/php_codesniffer:latest
      with:
        args: phpcs --standard=WordPress .

    - name: Build WordPress Theme/Plugin
      run: |
        cd wp-content/themes/your-theme
        composer install
        npm install
        npm run build

    - name: Archive Built Code
      run: tar -czf build.tar.gz wp-content

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build.tar.gz

  # Job 2: Deploy to EC2
  deploy:
    runs-on: ubuntu-latest
    needs: test-and-build  # Only run after test-and-build completes successfully

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Se
