name: Test, Build, and Deploy

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  # Job 1: Test and Build
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install PHP CodeSniffer
    - name: Install PHP CodeSniffer
      run: |
        curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        chmod +x phpcs.phar
        sudo mv phpcs.phar /usr/local/bin/phpcs

    # Clone WordPress Coding Standards repository
    - name: Clone WordPress Coding Standards
      run: |
        git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git /tmp/wpcs

    # Configure PHP CodeSniffer to use WordPress Coding Standards
    - name: Configure PHP CodeSniffer for WPCS
      run: phpcs --config-set installed_paths /tmp/wpcs

    # Run WordPress Coding Standards on the theme
    - name: Run WordPress Coding Standards
      run: phpcs --standard=WordPress wp-content/themes/twentytwentythree

    # Archive Built Code
    - name: Archive Built Code
      run: tar -czf build.tar.gz wp-content

    # Upload Build Artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build.tar.gz

  # Job 2: Deploy to EC2
  deploy:
    runs-on: ubuntu-latest
    needs: test-and-build  # Only run after test-and-build completes successfully

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to EC2
      run: |
        scp -o StrictHostKeyChecking=no build.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.HOST_IP }}:/tmp/build.tar.gz
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HOST_IP }} << 'EOF'
          cd /var/www/demo
          tar -xzf /tmp/build.tar.gz -C .
          sudo systemctl restart nginx
        EOF

